apiVersion: v1
kind: Service

metadata:
  name: spring-service
  namespace: hana-app

spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000

---

apiVersion: v1
kind: Service

metadata:
  name: mysql-service
  namespace: hana-app

spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
