spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    # url: jdbc:mysql://mysql-service:3306/sample_app
    # username: root
    # password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver